def line():
    a=float(input("Ingrese el coeficiente A: "))
    b=float(input("Ingrese el coeficiente B: "))
    x1=float(input("Ingrese el coeficiente X1: "))
    x2=float(input("Ingrese el coeficiente X2: "))
    print(f"El coeficiente A de su ecuación de la recta es: {a}")
    print(f"El coeficiente B de su ecuación de la recta es: {b}")
    print(f"El coeficiente X1 de su ecuación de la recta es: {x1}")
    print(f"El coeficiente X2 de su ecuación de la recta es: {x2}\n")
    print(f"Para la siguiente ecuación:\n\tY = {a}X + {b}\n")
    print(f"Dados los siguientes puntos:\n\tP1 ({x1}, {a*x1+b})\n\tP2 ({x2}, {a*x2+b})\n")
    print(f"La distancia entre ellos es: {((x1-x2)**2 + ((a*x1+b)-(a*x2+b))**2)**(1/2)}")
